[gcp_credentials]
type = "service_account"
project_id = "bigdata-sprint"
private_key_id = "d62182c107f982d9c5d3af6399df76edcb488377"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7SU7nksIcs7f7
YcghHwLT7UlSjp0O2SDVKR+Qm2I1T8sNelk/CUP/WP/B6VwAM2sfX9Un5uWE6W7R
xJ4mVIv8KliIhJE6jWAR45Nq22pTxKLNUNc61YuSPDBgjOPOwWuiOPnGLJ+dJvKh
LMGGH3qnsAsAcCRgZq4nrErrTUvtc1xj7uZfdcHmk1tQ5pGSaBZULKWxulAVLf3D
HZFuxPT4OwzgHmBlhMG47EgfIVCKRo+vk18194xOKuJPYPSCoNMgWZtRkvA7GhEI
rGPR1dLdFEESQHjhadZ+IUYS906YHVNI1vPqmBQPfCJcLmpQT0hxDYsSI0uNIV8c
PXe8UOK3AgMBAAECggEALcMYXhoshxHc0zZNzdYDfWAeCeeh9cZVMPCW72EgSpGA
Nn9ePjpX3JVVDP8lxUDLHIPwlArlqyfUtbnawNfoyolYT6dAyzNPNZ/LXhFV9jj2
ZL+rj4stSuKdGYJjiZoWYDGWyncN2zrwjzRd5xVbBY1M6uL76Hg+dqAxQDSHaHHc
GPweEjYuVxaZr/7g6MUuW+e6Sfg3zSMcJRrMIOj70/TNsplP1qgeeozQX++CZZRg
70gEmFt8D6HwMfQNbpMJD6qhbIUEvh9i0Q5yXFXLM7pfg/qV1tQb5apt86HwGyiG
TRiw8br+Pxn4pAXKZZdcCJ/zHsEgPjWR2PwtihOrIQKBgQDkL3twqMXyvQJUtb0P
x4SXbnLwYqAONAxnQQtRME6EKFFB3rjAIgAdcG7SkmasWTZyQCD1Y+cyvFsacFCu
lTqfpUcnrLD64yf8XIftT6C2j8Tgd0nITy6Fm7IgTPEyC6JHji8sE+/uY4Yv/65L
KLo9/Rw8QW1Dz9nN34DBoveZ1wKBgQDSHZIlINttdukC2xExawAHkI5PS8DXJ+GE
eMzPT9y38/4iJDkzVQgzWAAUAxQ9jowzudlSDPT3XtzWJBr4T5Cef80Pkvh+wua9
QlTdCJqFOJs4soaw7qqiaUyVNN48wpGktcmho9YyWPaZKij49viaUuH9JyVsnezN
kcj049SiIQKBgQDOcRbgyhCsl8uwD+xIhl2zEz3xtYjQ0M4X7ITsoyOl9UPusC29
xgUMnVfmMoWpj9zuaI5o9EWLZVWXCd401NYA8Wr6vgYwNatLafuf+9aO1GtuGP4r
t1eDkWUKTBI7EMN0sXKEElWT+36/ljZ90Q8OXhxZd2f/XeDTnU3D4kjYaQKBgH4p
YVJH21lr99dOIJGytM7V/o0gaEcIXEIForysMFSH/cUUSQBIg2cI5OsfOi0IBakd
Y57/xqst2539CfClHan+BOvgDLNYZeGoDXq2qslpRtKRZ4yfkfd5EJHar8J99aOX
v9z9miSbBF7NUNLEwFsxfx5ZPgBtBv4cFjTtBAThAoGADg9n5Y3ub232g2A5Wh2u
utw15Fp0l/OOiPZENsS9L+FpyXceiUYxu1WRnWv/CTQMZqTpfkiIF7YXWwPsn7Ws
eI1tlmUC3gYyzcPfcg6dyeP0Zo1giS0R8t0fegvZlhzzIVaHJZ9AfiDls0ZbwMCA
8HzzhRaedH3IwR4+syatCH4=
-----END PRIVATE KEY-----
"""
client_email = "bq-streamlit-app@bigdata-sprint.iam.gserviceaccount.com"
token_uri = "https://oauth2.googleapis.com/token"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
client_id = "104800240992233056431"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bq-streamlit-app%40bigdata-sprint.iam.gserviceaccount.com"

[gcp_config]
bucket_name = "my-smart-ingest-bucket"